### PR TITLE
perfect timer display even on tablets

### PR DESCRIPTION
**Pull request by odmfl**
I closed the previous one and opened this one, I reduce the space between the keys, and I added a landscape layout for tablets.

### CODE REVIEW

**Comment by BlackyHawky** [comment]
As I said [here](https://github.com/BlackyHawky/New-Clock/pull/1#issuecomment-1957889827):

- _my priority is to get rid of as many duplicate files as possible, so we have to do everything to avoid restoring "layout-land/timer_setup_digits.xml".
Give me a little time and I'll run a few tests._

- _Please create a new branch for future new PRs; this allows you to update the main branch without interfering with your modification request; this also allows you to avoid having several commits that do not correspond to your modification.
Finally, I cannot make changes to your PR because you use the main branch which is protected._

With this commit fd9de38, we now have perfectly round keys and correctly defined margins without adding new files regardless of the device (phone or tablet). 😉

I'll let you test it and I'm waiting for your opinion.

**Comment by odmfl** [comment]
Hi, sorry again for earlier, I'm a bit messy.  I tried your changes, now the timer display is perfect on phones.  On tablets the display has remained identical to before, there are practically too many spaces.  I'm sending you some screen shots of the landscape view on the tablet between my edit and yours, I understand that using one less resource is better but the view is worse
Screenshot_2024-02-23-11-21-37-805
Screenshot_2024-02-23-10-36-25-596

**Comment by odmfl** [comment]
Yes now the display is optimal even on tablets in landscape. You can close this PR. Thank you very much.

Also investigate the bug related to alarms not sounding with the screen off and make changes with SDK 34 with the commits I sent you in the other closed PR

**Comment by BlackyHawky** [comment]
I can't close the PR for you.
In any case, you can do it because with the latest commits, everything is ok.

> Also investigate the bug related to alarms not sounding with the screen off and make changes with SDK 34 with the commits I sent you in the other closed PR

That's my priority, but I'll need your help to test it because I don't have any devices with SDK 34.
If we don't achieve a positive result, I'll put SDK 33 back on.

**Comment by odmfl** [comment]
I have devices with Android 14 I can test easily.

Let's say that the bug with the alarm not ringing when the screen is off currently affects all versions of Android. 

On Android 14 the crash is added when the alarm is set.

**Comment by BlackyHawky** [comment]
> Let's say that the bug with the alarm not ringing when the screen is off currently affects all versions of Android.

Are you sure of what you're saying because on my devices it works correctly. My devices have Android versions 12 & 13.

Just to be clear, are you talking about the phone switched off or just the screen?

**Comment by odmfl** [comment]
Hi, I tried last commit on various devices.  Devices with android 7, 11, 12, 13, 14. Devices that have pure android aosp, miui, etc.  The alarm does not sound if the screen is off.  The only device it works on is a Realme with Realme UI.  In the next few days I can also test on Samsung.  The problem occurs when the screen is turned off.

As for the alarm when the phone is turned off, fortunately it is not broken, it is called "Power off alarm" on phones with snapdragon, that works, the phone turns back on, this is another separate function

**Comment by odmfl** [comment]
This app is based on the AOSP clock, it shares most of the code.  This screen off error had occurred before, but was resolved with this one https://github.com/LineageOS/android_packages_apps_DeskClock/commit/db9eb2368d7c1441db01e6d9fb1a82648705b1ff
I had made a PR where I added this and more and it was resolved, now by changing the SDK it has recurred.  Unfortunately, every time you change the SDK the problem recurs and new solutions must be found.

**Comment by BlackyHawky** [comment]
> This app is based on the AOSP clock...

I noticed this and will merge some of their commits in the future.

I downgraded to SDK 33 with the commit 13639e9. Can you try again and tell me if it's ok please?

**Comment by BlackyHawky** [comment]
Thank you for all these tests. So now I know what to do as a modification.

This will not influence older versions of Android because if you read my modification carefully, I include the condition: `if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU)`.

I will make the changes soon.

**Pull request closed without merging**
