### PR TITLE
Round buttons in timer and fix space between buttons

### PR DESCRIPTION
**Pull request by odmfl**
I improved the view of the timer buttons by making them round, similar to how it was before, the view is much more beautiful. It also fits well in landscape on phones, but in landscape on tablets it still needs to be improved, perhaps it is better to restore layout-land/timer_setup_digits.xml for tablets

### CODE REVIEW

**Comment by BlackyHawky** [comment]
Hi odmfl. Thanks for working on this. I hadn't thought of using the `inset` parameter for buttons and it may indeed be a solution.
However, I have a few comments:

- my priority is to get rid of as many duplicate files as possible, so we have to do everything to avoid restoring "layout-land/timer_setup_digits.xml".
Give me a little time and I'll run a few tests.

- `inset` parameters can be specified in styles to avoid duplication;

- what's the point of indicating `app:cornerRadius`? The keys look round on emulator without this parameter.

**Comment by BlackyHawky** [comment]
You can test commit 6a771e0 which is closer to what I expect.

**Comment by odmfl** [comment]
I tried the changes, now the keys are perfectly circular, but there is still a lot of space between them, if you can reduce the space between the keys it would be perfect; however the tablet landscape issue presents the same error. I think the solution is to be found in timer_setup_view, however I will investigate further

**Comment by odmfl** [comment]
I noticed a very important bug, since changing the app to SDK 34, the alarm no longer sounds when the screen is off, it only sounds when the screen is on. I have tried on various phones with different versions of Android and they all give the same problem. 


As for phones running Android 14, this crash occurs , log 

https://bin.kv2.dev/~65cca18c5de7ed6bfdbd8a26

this is solved with this commit, 

https://github.com/crdroidandroid/android_packages_apps_DeskClock/commit/1d20659afba8782156f6d100271a9831e562c873

only that you have to raise min sdk to 26, 
you have to find an alternative solution

**Pull request closed without merging**
